### ISSUE TITLE
Replace repeated compilaton key with a function.

### ISSUE THREAD

**Issue by bartoszziemba** [52ym0n/vector_gradebook#1]
In https://github.com/52ym0n/vector_gradebook/commit/afa1265e825f7686c854c343d0290deb54fcf442 there is a compilation key introduced that is repeated the same way over three files like this:

https://github.com/52ym0n/vector_gradebook/blob/36e4a5a1f35cf148740adb2ed4a78dd5b3fcbfaf/src/Eval.c#L8-L12

I suggest that a overlay funciton is created to hide this from the user.

**Comment by 52ym0n** [comment]
the commit c06da02 solved the issue...
